"""add webhook retry fields

Revision ID: 20df30bb35bd
Revises: 8ad4fb26e434
Create Date: 2026-04-06 16:12:15.966335

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20df30bb35bd'
down_revision: Union[str, Sequence[str], None] = '8ad4fb26e434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('webhook_events', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhook_events', sa.Column('last_error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'last_error')
    op.drop_column('webhook_events', 'last_attempt_at')
    op.drop_column('webhook_events', 'retry_count')
    # ### end Alembic commands ###
