"""remove extra_data column from payment_intents

Revision ID: 2a27359887c4
Revises: 20df30bb35bd
Create Date: 2026-04-14 14:02:33.929479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a27359887c4'
down_revision: Union[str, Sequence[str], None] = '20df30bb35bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_intents', 'extra_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intents', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
